language: php
php:
  - '7.3.5'
services:
  - postgresql

env:
  - DATABASE_URL=pgsql://NameUserDatabase:PasswordDatabase@127.0.0.1:5432/$NameDatabase
  before_script:
  - psql -c 'create database slamquiz;' -U postgres
  - psql -c "CREATE USER slamquiz With password 'Admin';" -U postgres

script:
  - composer install
  - php bin/console doctrine:schema:update --force 
  - php bin/console doctrine:fixtures:load -n 
  - php bin/phpunit
   
