language: php
php:
  - '7.3.5'
services:
  - postgresql
before_script:
  - psql -c 'create database slamquiz;' -U postgres
  - psql -c "CREATE USER slamquiz With password 'Admin';" -U postgres

script:
  - composer install
  - php bin/console doctrine:schema:update --force -e=test 
  - php bin/console doctrine:fixtures:load -n -e=test
  # - php bin/phpunit
   
