language: php
php:
  - '7.3.5'
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
script:
  - composer install
  - composer require --dev symfony/phpunit-bridge
  - php bin/console doctrine:fixtures:load -n 
  - php bin/phpunit
   
